site_name: Build your first modern data stack
site_url: https://example.com
repo_url: https://github.com/glsdown/modern-data-stack-build
nav:
  - Home: index.md
  - Getting Started:
      - Initial Setup:
          - getting-started/initial-setup/index.md
          - GitHub Setup: getting-started/initial-setup/1-github-setup.md
          - Local Environment: getting-started/initial-setup/2-local-environment.md
          - Development Workflow: getting-started/initial-setup/3-development-workflow.md
          - Secrets Management: getting-started/initial-setup/4-secrets-management.md
      - Hosted Accounts Setup:
          - getting-started/account-setup/index.md
          - Costs: getting-started/account-setup/costs.md
          - AWS: getting-started/account-setup/aws.md
          - Snowflake: getting-started/account-setup/snowflake.md
      - Terraform Setup:
          - getting-started/terraform-setup/index.md
          - Set Up Remote State: getting-started/terraform-setup/1-set-up-terraform-remote-state.md
          - Set Up Terraform Locally: getting-started/terraform-setup/2-set-up-terraform-locally.md
          - Create Terraform Repository: getting-started/terraform-setup/3-create-the-terraform-repo.md
          - Add GitHub to Terraform:
              - getting-started/terraform-setup/github/index.md
              - Set Up Backend: getting-started/terraform-setup/github/1-setup-github-backend.md
              - Import Organisation: getting-started/terraform-setup/github/2-import-github-organisation.md
              - Import Teams: getting-started/terraform-setup/github/3-import-github-teams.md
              - User Management: getting-started/terraform-setup/github/4-github-user-management.md
              - Finishing Up: getting-started/terraform-setup/github/5-finishing-up.md
          - Deploy with CI/CD: getting-started/terraform-setup/4-terraform-deployment.md
          - Add AWS to Terraform:
              - getting-started/terraform-setup/aws/index.md
              - Set Up Backend: getting-started/terraform-setup/aws/1-setup-aws-backend.md
              - Import IAM Roles: getting-started/terraform-setup/aws/2-import-iam-roles.md
              - Import State Infrastructure: getting-started/terraform-setup/aws/4-import-state-infrastructure.md
              - Import IAM Users: getting-started/terraform-setup/aws/5-import-iam-users.md
              - Import Budget Alerts: getting-started/terraform-setup/aws/6-import-budget-alerts.md
              - Secrets Manager Setup: getting-started/terraform-setup/aws/7-secrets-manager-setup.md
              - Finishing Up: getting-started/terraform-setup/aws/8-finishing-up.md
theme:
  name: material
  font:
    text: Raleway
  favicon: images/favicon.png
  icon:
    logo: fontawesome/solid/cubes-stacked
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    # Don't fully reload the page for internal links
    - navigation.instant
    # Inject anchors into the URL
    - navigation.tracking
    # Allow section headings to have their own pages
    - navigation.indexes
    # Automatically scroll navigation sidebar to location on page
    - toc.follow
plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.keys
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/glsdown
  # Don't show this is material for mkdocs
  generator: false
